services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
      - "30000:8888"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: .
        target: /autofl

  ui:
#    profiles:
#      - ui
    build:
      context: autofl-ui/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8501:8501"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: ./autofl-ui/
        target: /autofl-ui
    links:
      - 'api:auto-fl'