[tool.poetry]
name = "autofl"
version = "0.1.1"
description = ""
authors = ["Cezar Sas <cezar.sas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.97.0"
gunicorn = "^20.1.0"
uvicorn = "^0.22.0"
pandas = "^2.0.2"
hydra-core = "^1.3.2"
setuptools = "^67.8.0"
antlr4-python3-runtime = "4.9.3"
multiset = "^3.0.1"
scikit-learn = "^1.2.2"
pydantic = "^1.10.9"
gitpython = "^3.1.31"


[tool.poetry.group.dev.dependencies]
notebook = "^6.5.4"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
