[tool.poetry]
name = "autofl"
version = "0.1.1"
description = ""
authors = ["Cezar Sas <cezar.sas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.1"
gunicorn = "^21.2.0"
uvicorn = "^0.23.2"
pandas = "^2.1.0"
hydra-core = "^1.3.2"
setuptools = "^68.2.0"
multiset = "^3.0.1"
scikit-learn = "^1.3.0"
pydantic = "^2.3.0"
gitpython = "^3.1.35"
loguru = "^0.7.1"
tqdm = "^4.66.1"
#yake = { git = "git@github.com:LIAAD/yake.git" }
python-rake = "^1.5.0"
more-itertools = "^10.1.0"
tree-sitter = "^0.20.2"

[tool.poetry.group.dev.dependencies]
notebook = "^6.5.4"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
