[tool.poetry]
name = "autofl"
version = "0.1.1"
description = ""
authors = ["Cezar Sas <cezar.sas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.98.0"
gunicorn = "^20.1.0"
uvicorn = "^0.22.0"
pandas = "^2.0.2"
hydra-core = "^1.3.2"
setuptools = "^68.0.0"
multiset = "^3.0.1"
scikit-learn = "^1.2.2"
pydantic = "^1.10.9"
gitpython = "^3.1.31"
loguru = "^0.7.0"
tqdm = "^4.65.0"
yake = { git = "git@github.com:LIAAD/yake.git" }
python-rake = "^1.5.0"
more-itertools = "^9.1.0"
tree-sitter = "^0.20.1"

[tool.poetry.group.dev.dependencies]
notebook = "^6.5.4"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
