# @package _global_
base_path: /autofl
data_path: ${base_path}/data
raw_data_path: ${data_path}/raw
repository_path: ${raw_data_path}/repository
test_data_path: ${data_path}/test
grammars_path: ${data_path}/grammars/
languages_library: ${grammars_path}/languages.so
models_path: ${data_path}/models