# @package _global_
base_path: /home/sasce/PycharmProjects/AutoFL
data_path: ${base_path}/data
raw_data_path: ${data_path}/raw
repository_path: ${raw_data_path}/repository
test_data_path: ${data_path}/test