# @package _global_
defaults:
  - _self_
  - local: docker
  - taxonomy: gitranking
  - annotator: test
  - version_strategy: latest
  - dataloader: postgres

hydra:
  output_subdir: null
  run:
    dir: .