# @package _global_
defaults:
  - _self_
  - local: docker
  - taxonomy: small
  - lf: keyword
  - filtering: none
  - transformation: none
  - version_strategy: latest_strategy

hydra:
  output_subdir: null
  run:
    dir: .