# @package _global_
defaults:
  - _self_
  - environment: docker
  - run: batch_annotation

package_annotation: True
project_annotation: True

n_workers: 1

hydra:
  output_subdir: null
  run:
    dir: .