# @package _global_
defaults:
  - _self_
  - local: default
  - taxonomy: small
  - annotator: default
  - version_strategy: latest
  - dataloader: gitranking

hydra:
  output_subdir: null
  run:
    dir: .