name: mkdocs

on:
  push:
    branches: [ dev-doc ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install requirements
        run: python3 -m pip install -r mkdocs_requirements.txt

      - name: Deploy 🚀
        run: python3 -m mkdocs gh-deploy --force